import { StyleSheet } from "react-native";
import { size } from "../../helpers/normalize";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  rowItem: {
    width: "90%",
    height: size(64),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    borderWidth: 1,
    alignSelf: "center",
    margin: 8,
    backgroundColor: "#fff",
    borderColor: "#FE6B8B",
  },
  helperText: {
    alignSelf: "center",
    textAlign: "center",
    width: "90%",
    fontFamily: "open-sans",
  },
  button: {
    width: "90%",
    alignSelf: "center",
    height: 54,
    borderRadius: 8,
    position: "absolute",
    bottom: 40,
    overflow: "hidden",
  },
  buttonBackground: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  buttonText: {
    fontSize: 24,
    color: "white",
    fontWeight: "bold",
    fontFamily: "open-sans-bold",
  },
  clockItem: {
    width: "95%",
    height: "40%",
    alignSelf: "center",
    backgroundColor: "#bbb",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "space-between",
    //padding: 8,
    margin: 8,
    elevation: 5,
    shadowColor: "black",
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 3,
  },
  clockItemTime: {
    fontSize: 48,
    color: "white",
    fontWeight: "bold",
    letterSpacing: 1.2,
    fontFamily: "open-sans-extra-bold",
  },
  clockItemMoves: {
    fontSize: 28,
    color: "white",
    fontWeight: "bold",
    letterSpacing: 1.2,
    padding: 8,
    fontFamily: "open-sans-extra-bold",
  },
  clockMenu: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: "15%",
    justifyContent: "space-evenly",
  },
  clockMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    width: "33%",
    justifyContent: "center",
  },
  clockFaceLinearGradient: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: "100%",
    borderRadius: 8,
  },
  timerMenuText: {
    fontSize: 16,
    fontFamily: "open-sans",
    color: "black",
  },
});
