import { StyleSheet, Dimensions } from "react-native";
import { size } from "../../helpers/normalize";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    //justifyContent: "center",
    backgroundColor: "white",
    alignItems: "center",
  },
  inputContainer: {
    width: "100%",
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    marginBottom: 12,
  },
  input: {
    width: "100%",
    height: size(56),
    fontSize: 24,
    textAlignVertical: "center",
    textAlign: "center",
    fontFamily: "open-sans",
    borderBottomWidth: 1.5,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    backgroundColor: "#f9f9f9",
    borderColor: "#eee",
    borderBottomColor: "#FF8E53",
  },
  inputLabelContainer: {
    width: Dimensions.get("screen").width * 0.5,
    marginHorizontal: 16,
  },
  labelStyle: {
    marginVertical: 4,
    fontFamily: "open-sans",
  },
  plusButton: {
    width: size(35),
    height: size(35),
    borderRadius: size(20),
    justifyContent: "center",
    alignItems: "center",
    //backgroundColor: "purple",
    marginHorizontal: 12,
    overflow: "hidden",
  },
  minusButton: {
    width: size(35),
    height: size(35),
    borderRadius: size(20),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#aaa",
    marginHorizontal: 12,
  },
  button: {
    width: "90%",
    //position: "absolute",
    //bottom: 40,
    height: 56,
    alignSelf: "center",
    borderRadius: 8,
    zIndex: 2000,
    overflow: "hidden",
  },
  buttonBackground: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    width: "100%",
    height: "100%",
  },
  buttonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    letterSpacing: 1.2,
    fontFamily: "open-sans-bold",
  },
  resultsContainer: {
    width: "90%",
    padding: 16,
    flexDirection: "row",
    marginVertical: 16,
    alignItems: "center",
    justifyContent: "space-evenly",
    flexWrap: "wrap",
  },
  result: {
    fontSize: 36,
    color: "black",
    margin: 16,
    fontWeight: "bold",
    fontFamily: "open-sans-bold",
  },
});
