import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#eee",
  },
  sectionHeader: {
    width: "100%",
    height: 56,
    backgroundColor: "#eee",
    paddingHorizontal: 16,
    justifyContent: "flex-end",
    paddingVertical: 8,
    borderBottomWidth: 2,
    borderBottomColor: "#aaa",
  },
  headerText: {
    textAlign: "left",
    textAlignVertical: "bottom",
    fontSize: 14,
    color: "#aaa",
    fontFamily: "open-sans",
  },
  rowItem: {
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 48,
    paddingHorizontal: 16,
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  textLabel: {
    color: "black",
    opacity: 0.6,
    fontFamily: "open-sans",
  },
  textData: {
    color: "black",
    opacity: 0.87,
    fontSize: 15,
    fontFamily: "open-sans",
  },
  save: {
    color: "blue",
    opacity: 0.87,
    fontFamily: "open-sans",
  },
  penColorButton: {
    width: 36,
    height: 36,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  historyItem: {
    width: "100%",
    borderBottomWidth: 0.5,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    padding: 12,
  },
  historyItemText: {
    fontSize: 15,
    fontFamily: "open-sans",
  },
  input: {
    flex: 1,
    height: "90%",
    marginLeft: 12,
    borderWidth: 1,
    fontFamily: "open-sans",
    textAlignVertical: "center",
    textAlign: "right",
    borderRadius: 8,
    paddingHorizontal: 12,
    borderColor: "white",
  },
  inputError: {
    borderColor: "red",
  },
});
