import { StyleSheet } from "react-native";
import { size } from "../../helpers/normalize";

export const styles = StyleSheet.create({
  container: {
    width: "90%",
    borderRadius: 8,
    elevation: 4,
    shadowColor: "black",
    shadowOffset: { width: 4, height: 6 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    //height: 80,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    alignSelf: "center",
    marginVertical: 10,
  },
  header: {
    width: "100%",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 64,
  },
  input: {
    flex: 1,
    height: "100%",
    fontSize: 24,
    fontFamily: "open-sans",
    textAlign: "center",
    borderBottomWidth: 1,
  },
  iconButton: {
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  value: {
    fontSize: 60,
    fontWeight: "bold",
  },
  valueContainer: {
    width: "100%",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  plusButton: {
    width: size(35),
    height: size(35),
    borderRadius: size(20),
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 12,
    overflow: "hidden",
  },
  minusButton: {
    width: size(35),
    height: size(35),
    borderRadius: size(20),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#aaa",
    marginHorizontal: 12,
  },
  buttonBackground: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    width: "100%",
    height: "100%",
  },
  buttonContainer: {
    flexDirection: "row",
    width: "100%",
    height: 44,
    borderTopWidth: 0.5,
    overflow: "hidden",
  },
  accessoryButton: {
    justifyContent: "center",
    alignItems: "center",
    width: "20%",
    height: "100%",
    overflow: "hidden",
  },
  verticalDivider: { height: "100%", width: 0, borderWidth: 0.5 },
  incrementValueButton: {
    fontSize: 20,
    fontFamily: "open-sans",
  },
  menuTitle: {
    fontSize: 16,
    fontFamily: "open-sans-bold",
    marginVertical: 8,
  },
  incrementInput: {
    width: "90%",
    borderBottomWidth: 1,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderColor: "#FF8E53",
    paddingHorizontal: 12,
    height: 56,
    marginTop: 8,
    fontSize: 18,
    fontWeight: "500",
    backgroundColor: "#eee",
    color: "#323232",
  },
  saveButton: {
    width: "100%",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FF8E53",
    marginTop: 24,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  saveButtonText: {
    fontSize: 20,
    color: "white",
    fontFamily: "open-sans-bold",
  },
});
