import { StyleSheet } from "react-native";
import { size } from "../../helpers/normalize";

export const styles = StyleSheet.create({
  die: {
    width: size(64),
    height: size(64),
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    resizeMode: "cover",
    width: "100%",
    height: "100%",
  },
  diceValue: {
    position: "absolute",
    alignSelf: "center",
    zIndex: 15,
    fontSize: size(28),
    fontWeight: "bold",
    fontFamily: "open-sans-bold",
  },
  diceContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    backgroundColor: "white",
  },
  diceItemContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    justifyContent: "space-evenly",
    margin: 8,
  },
  changeNumberButton: {
    width: size(35),
    height: size(35),
    borderRadius: size(20),
    marginHorizontal: 12,
    overflow: "hidden",
  },
  dieItem: {
    //alignItems: "center",
  },
  dieCountText: {
    alignSelf: "center",
    fontSize: 18,
    fontWeight: "700",
    fontFamily: "open-sans-bold",
  },
  animatedView: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
    zIndex: 10,
    elevation: 3,
  },
  selectDiceButton: {
    width: "100%",
    height: size(125),
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 16,
    backgroundColor: "#eee",
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    shadowColor: "#aaa",
    shadowOffset: { width: 3, height: 5 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
    elevation: 2,
  },
  selectDieContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
  },
  selectDice: {
    position: "absolute",
  },
  selectDiceText: {
    marginVertical: 8,
    fontSize: 20,
    fontWeight: "500",
    fontFamily: "open-sans",
  },
  button: {
    width: "90%",
    position: "absolute",
    bottom: 40,
    height: 56,
    alignSelf: "center",
    borderRadius: 8,
    zIndex: 2000,
    elevation: 5,
    overflow: "hidden",
  },
  buttonBackground: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  buttonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    letterSpacing: 1.2,
    fontFamily: "open-sans-bold",
  },
  resultsContainer: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-evenly",
    marginVertical: 24,
  },
  resultsText: {
    fontWeight: "bold",
    fontSize: 26,
    color: "black",
    fontFamily: "open-sans-bold",
  },
});

export const dieFaceSet = {
  d4: require("../../assets/d4.png"),
  d6: require("../../assets/d6.png"),
  d8: require("../../assets/d8.png"),
  d10: require("../../assets/d10.png"),
  d12: require("../../assets/d12.png"),
  d20: require("../../assets/d20.png"),
  d100: require("../../assets/d100.png"),
};
