import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    margin: 8,
  },
  inputItem: {
    marginVertical: 16,
    width: "90%",
    alignSelf: "center",
  },
  inputContainer: {
    width: "100%",
    height: 56,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#FE6B8B",
    backgroundColor: "rgba(174, 174, 174, .4)",
  },
  input: {
    width: "100%",
    height: "100%",
    padding: 12,
    fontSize: 20,
    color: "black",
  },
  inputLabel: {
    fontSize: 16,
    paddingVertical: 8,
  },
  button: {
    width: "90%",
    height: 56,
    alignSelf: "center",
    borderRadius: 8,
    marginVertical: 24,
    overflow: "hidden",
  },
  buttonBackground: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  buttonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    letterSpacing: 1.2,
  },
  addPlayerButton: {
    width: "90%",
    height: 56,
    //backgroundColor: "blue",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    alignSelf: "center",
  },
  addPlayerButtonText: {
    fontSize: 20,
    color: "white",
    fontWeight: "bold",
    letterSpacing: 1.2,
  },
  playerCard: {
    width: "90%",
    height: 56,
    marginVertical: 8,
    justifyContent: "space-between",
    paddingHorizontal: 12,
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    borderRadius: 4,
    borderWidth: 1.25,
    borderColor: "#FE6B8B",
  },
  playerNameLabel: {
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: 1.1,
    color: "black",
  },
  playerNameIconButton: {
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  rowStyles: {
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "space-between",
  },
});
