import { Dimensions, StyleSheet } from "react-native";

const screen = Dimensions.get("window");
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    //justifyContent: "center",
  },
  timerContainer: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    height: 125,
  },
  msText: {
    fontSize: 36,
    width: 64,
    height: "100%",
    //borderWidth: 2,
    textAlign: "left",
    paddingTop: 46.5,
    position: "relative",
    fontFamily: "open-sans-bold",
  },
  buttonBackground: {
    width: screen.width / 2,
    height: screen.width / 2,
    borderRadius: screen.width / 2,
  },

  button: {
    borderWidth: 10,
    borderColor: "#B9AAFF",
    width: screen.width / 2,
    height: screen.width / 2,
    borderRadius: screen.width / 2,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  gradient: {
    width: screen.width / 2 + 10,
    height: screen.width / 2 + 10,
    borderRadius: screen.width / 2 + 10,
    overflow: "hidden",
    margin: 10,
  },
  button2: {
    width: screen.width / 2 - 10,
    height: screen.width / 2 - 10,
    borderRadius: screen.width / 2 - 10,
    backgroundColor: "white",
    zIndex: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    fontSize: 45,
    color: "#B9AAFF",
    zIndex: 100,
    fontFamily: "open-sans-bold",
  },
  timerText: {
    //color: "#fff",
    color: "black",
    fontSize: 64,
    //marginBottom: 20,
    fontFamily: "open-sans-bold",
  },
  buttonReset: {
    marginTop: 20,
    borderColor: "#FF851B",
  },
  buttonTextReset: {
    color: "#FF851B",
    zIndex: 100,
  },
  footer: {
    position: "absolute",
    bottom: 0,
    height: 96,
    width: "100%",
    justifyContent: "space-evenly",
    alignItems: "center",
    backgroundColor: "transparent",
    flexDirection: "row",
  },
  footerGradient: {
    width: 60,
    height: 60,
    borderRadius: 60,
  },
  footerButton2: {
    width: 50,
    height: 50,
    borderRadius: 50,
  },
  lapRowItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    padding: 8,
  },
  lapRowItemSection: {
    flexDirection: "row",
    justifyContent: "center",
    width: "25%",
  },
  lapRowItemText: {
    fontSize: 18,
    fontFamily: "open-sans",
    color: "white",
    opacity: 0.6,
  },
  lapContainer: {
    elevation: 4,
    zIndex: 5,
    height: 300,
    shadowColor: "#171717",
    shadowOffset: { width: 6, height: 9 },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    width: "80%",
    borderRadius: 16,
    borderWidth: 0.25,
    borderColor: "#f9f9f9",
  },
});
