import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("screen");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  inputContainer: {
    marginVertical: 16,
    width: "90%",
    height: 56,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomWidth: 1,
    borderBottomColor: "blue",
    alignSelf: "center",
    backgroundColor: "rgba(174, 174, 174, .4)",
  },
  input: {
    width: "100%",
    height: "100%",
    padding: 12,
    fontSize: 20,
    color: "black",
  },
  addPlayerButton: {
    width: "90%",
    height: 56,
    backgroundColor: "blue",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    alignSelf: "center",
  },
  addPlayerButtonText: {
    fontSize: 20,
    color: "white",
    fontWeight: "bold",
    letterSpacing: 1.2,
  },
  playerCard: {
    width: "90%",
    height: 56,
    marginVertical: 8,
    justifyContent: "space-between",
    paddingHorizontal: 12,
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    borderRadius: 4,
    borderWidth: 1.25,
  },
  playerNameLabel: {
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: 1.1,
    color: "black",
  },
  playerNameIconButton: {
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  gameTurnHeader: {
    width: "100%",
    height: 56,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  gameTurnHeaderText: {
    fontSize: 28,
    fontWeight: "bold",
  },
  gameSectionHeader: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    width: "100%",
    borderTopWidth: 1,
    borderBottomWidth: 1,
  },
  gameSectionHeaderTitle: {
    fontSize: 18,
    fontWeight: "bold",
    margin: 8,
  },
  gameSectionHeaderSubTitle: {
    fontSize: 14,
  },
  gameSectionCell: {
    paddingHorizontal: 8,
    paddingVertical: 12,
    width: "25%",
    justifyContent: "center",
    alignItems: "center",
  },
  scorePickerButton: {
    width: width * 0.25,
    height: 64,
    justifyContent: "center",
    alignItems: "center",
  },
  scorePickerText: {
    fontSize: 18,
    color: "black",
    padding: 12,
  },
  scorePickerTextUnderline: {
    height: 0,
    alignSelf: "center",
    width: width * 0.2,
    borderWidth: 1,
    borderColor: "#aaa",
  },
  button: {
    width: "90%",
    position: "absolute",
    bottom: 40,
    backgroundColor: "blue",
    justifyContent: "center",
    alignItems: "center",
    height: 56,
    alignSelf: "center",
    borderRadius: 8,
    zIndex: 2000,
  },
  buttonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    letterSpacing: 1.2,
  },
});
