import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#eee",
  },
  scores: {
    width: "100%",
    height: 139,
    alignItems: "center",
    flexDirection: "row",
  },
  entry: {
    width: "100%",
    height: 75,
    zIndex: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(46, 204, 113, .8)",
    position: "absolute",
    top: 0,
  },
  animatedView: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
    zIndex: 10,
    elevation: 3,
    //backgroundColor: "#8ED1FC",
    backgroundColor: "#323232",
  },
  listHeaderContainer: {
    width: "100%",
    height: 64,
    flexDirection: "row",
    alignItems: "center",
    //borderBottomWidth: 3,
    borderColor: "white",
    //backgroundColor: "#8ED1FC",
    backgroundColor: "#FF8E53",
  },
  listHeaderItem: {
    width: "50%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  listHeaderItemText: {
    fontSize: 28,
    fontFamily: "open-sans-bold",
    color: "white",
    //color: "#8ED1FC",
  },
  logItemContainer: {
    width: "100%",
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 0.25,
    borderBottomWidth: 0.25,
    //borderColor: "white",
  },
  logItem: {
    width: "50%",
    height: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    //borderWidth: 0.25,
    //borderColor: "white",
  },
  logItemText: {
    fontSize: 24,
    color: "white",
    fontFamily: "open-sans",
  },
  logDoneButtonContainer: {
    width: "50%",
    height: 56,
    alignSelf: "center",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  logDoneButtonText: {
    fontSize: 20,
    fontFamily: "open-sans-bold",
    color: "#0693E3",
  },
  addBorderRight: {
    borderRightWidth: 0.5,
    borderColor: "white",
  },
  addBorderLeft: {
    borderLeftWidth: 0.5,
    borderColor: "white",
  },
});
